version: "3.7"

services:
  service-ts:
    image: node:16-alpine
    command: sh -c "npm i && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    tty: true
